### ISSUE TITLE
Argument with Comma vs Multi-Argument Role

### ISSUE THREAD

**Issue by JosephGatto** [Milind21/qag_ee#1]
Hi, 

Thanks for constructing such an awesome dataset! Quick question. Is there any good way to determine if a question has multiple answers vs a single answer containing a comma? 

Thanks!

**Comment by Milind21** [comment]
Hi,
The way the dataset is currently designed, there should not be a question with multiple answers. I have QA pairs in which there is one question with corresponding answers. Can you provide an example so I can take a look?
Regards,
Milind

**Comment by JosephGatto** [comment]
Hi Milind, 

So my question is motivated by this passage in the paper: 

> However, questions can have multiple answer spans. An example is “What was Mr. Dash expected to have” whose answer can be “kindness, confidence”. We have additional guidelines that ensure answers are from d.


Here is an example in the dataset I am referring to: 

> Question: Who was speaking when the assassination attempt occurred?
> Answer: the president, Nicolás Maduro
> Document: Venezuela’s president, **Nicolás Maduro**, has survived an apparent and – if true – audacious assassination attempt when, according to official reports, drones loaded with explosives flew towards **the president** while he was speaking at a mil [truncated full document]


Here, there are two different answer spans in the document for this question. Sorry if I misspoke as these are the same answer, but different spans/expressions of the answer.

**Comment by Milind21** [comment]
Hi Joseph, 
So during the intial guidelines we mention the annotators to match the answers to be as near the trigger as possible. While prompting to the LMs we do the same thing. Sorry if the language was a bit confusing. 
We also observed, most of the time even if it had multiple spans the answers were quite consistent possibly with some kind of grammatical alteration.
Regards, 
Milind

**Comment by JosephGatto** [comment]
Thanks Milind. One last clarification. So in the example I attached it does appear there are two different phrasings of the same answer to the same question and it is annotated as such. So is it the case that this happens sometimes (perhaps rarely) and isn't in-general handled any differently?

**Comment by Milind21** [comment]
Hey Joseph, 
For the set of documents which we encountered, this happened very rarely and even in such cases (as the one which you mentioned) the answer remained the same. But a robust handling pipeline can be developed in case of scaling it up. Thanks for the observation!
